### ISSUE TITLE
About Skip.

### ISSUE THREAD

**Issue by thautwarm** [thautwarm/Linq.py#4]
@Athedorer 
I'd like to assign new meanings to `Skip` because its current semantics  are duplicated by `Drop`.
```Python
Flow([1, 2, 3, 4, 5]).SKip(1).ToList()
# => [1, 3, 5] 
```
How do you think about it?

**Comment by arlor** [comment]
@thautwarm 
I support. 
And I want to say something about **Unboxed**. People may forget to call **Unboxed** when they want to get the result from **Flow**, just as you did it. In my opinion, actions such as **Sum**, **ToList**, **Reduce** may take the responsibility for **Unboxed** to get the result directly, and **Unboxed** should be called explicitly to trigger the evaluation to those transformations such as **Take**, **Scan** . It is easy to distinguish between actions and transformations: if the operation change the type of stream in **Flow**, it's action, otherwise it's transformation. Just a suggestion, what do you think?

**Comment by thautwarm** [comment]
Firstly I didn't forget, but `Flow`'s meta method`__str__` will call those of the unboxed ones. 
Next, there could be some obstacles to agree with you.
Think about this case:
```python
Flow([[1, 2], [3, 4], [5, 6]]).Sum().Each(print)  
# although current `Sum` do not support list summary 
```
It's certainly possible that method `Sum`  returns a sequence, so it might still need to do `linq` operations(chaining call) then.  
I prefer to give only one method to unbox. But your suggestions could be useful —— I think it interesting to use `Trigger` in `Linq`, which makes it possible to do optimizations, so let us hold this problem until we come to  an agreement.
(For immutable data, we should use transformations instead of actions as possible as we can.
